services:
  jekyll-site:
    build: .
    image: vitorholanda/website:latest
    container_name: vitor_website2
    restart: always
    ports:
      - "127.0.0.1:4000:8080"
    read_only: true
    user: "101:101"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    pids_limit: 100
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=16m
